// Generates docs/asset-inventory.md and docs/project-inventory.md from the same data the site renders.
// Usage: npx tsx scripts/inventory.ts
import fs from 'node:fs';
import path from 'node:path';
import { entries, statusLabel, categories } from '../src/data/work';
import { cases } from '../src/data/cases';
import { tools } from '../src/data/tools';
import { reviews } from '../src/data/site';

const root = path.resolve(path.dirname(new URL(import.meta.url).pathname), '..');
const media = JSON.parse(fs.readFileSync(path.join(root, 'src/data/media.json'), 'utf8'));
const logs = Object.assign({}, ...fs.readdirSync(path.join(root, 'capture/reports')).filter((f) => f.startsWith('capture-log')).map((f) => JSON.parse(fs.readFileSync(path.join(root, 'capture/reports', f), 'utf8'))));
const links = JSON.parse(fs.readFileSync(path.join(root, 'capture/reports/links.json'), 'utf8'));
const linkStatus = new Map(links.results.map((r: any) => [r.url, r]));
const du = (dir: string) => {
  let n = 0;
  if (!fs.existsSync(dir)) return 0;
  for (const f of fs.readdirSync(dir)) n += fs.statSync(path.join(dir, f)).size;
  return n;
};

const OWN = /mousabatarseh\.com|asas\.build|moseswebworks\.com|mousabb2\.chatgpt\.site/;
const licence = (url: string) => (OWN.test(url) ? 'Own work (Mousa’s site or tool)' : 'Client site Mousa built or ran — screenshot used for portfolio; confirm client is happy to be shown');

// Where each capture appears on the site.
const placements = new Map<string, Set<string>>();
const place = (slug: string | undefined, where: string) => { if (!slug) return; if (!placements.has(slug)) placements.set(slug, new Set()); placements.get(slug)!.add(where); };
for (const c of cases) {
  place(c.media.hero, `/work/${c.slug}/ hero, exploded plates, OG card`);
  if (c.media.full) place(c.media.full, `/work/${c.slug}/ full-page frame`);
  if (c.media.mobile) place(c.media.mobile, `/work/${c.slug}/ mobile frame`);
  if (c.media.video) place(c.media.video, `/work/${c.slug}/ recordings`);
  c.media.more?.forEach((m) => place(m.slug, `/work/${c.slug}/ “also part of this work”`));
  if (c.group === 'sites') place(c.media.hero, 'home: featured plate');
}
tools.forEach((t) => place(t.media, 'home: tools rack'));
reviews.forEach((r) => place(r.media, 'home: counted reviews'));
entries.forEach((e) => place(e.media, '/work/ archive loupe + thumbnail'));

const rows: string[] = [];
let total = 0;
for (const [slug, m] of Object.entries<any>(media).sort()) {
  const log = logs[slug] || {};
  const bytes = du(path.join(root, 'public/media', slug));
  total += bytes;
  const views = Object.keys(m.views).join(', ');
  const recs = [m.video && `scroll ${Math.round(m.video.seconds || 0)} s`, m.interaction && `interaction ${Math.round(m.interaction.seconds || 0)} s`].filter(Boolean).join(' · ');
  const gates = [...new Set(Object.values<any>(log.views || {}).flatMap((v) => v.gates?.actions || []))].join('; ');
  const det = (m.details || []).map((d: any) => d.label).join('; ');
  rows.push(`| \`${slug}\` | ${m.url || log.url || ''} | ${(m.capturedAt || log.capturedAt || '').slice(0, 10)} | ${views}${recs ? ' · ' + recs : ''}${det ? ` · details: ${det}` : ''} | ${[...(placements.get(slug) || ['not used on the site'])].join('; ')} | ${gates || '—'} | ${licence(m.url || log.url || '')} | ${(bytes / 1024 / 1024).toFixed(1)} MB |`);
}

const assetDoc = `# Asset inventory

Generated by \`scripts/inventory.ts\` from \`src/data/media.json\` and the capture logs. Every image and video on the site is a real capture of Mousa's own work, made in a real browser (Chromium via Playwright on GitHub Actions, 1440×900 desktop and 390×844 mobile). Nothing was bought, no stock or AI imagery is used, and no reference-site imagery is stored anywhere in this repository.

- **Raw captures** live in \`capture/raw/<slug>/\` (full-resolution WebP stills, layout outlines, recordings). Capture logs with every page status and every dismissed dialog are in \`capture/reports/\`.
- **Web media** in \`public/media/<slug>/\` are derived by \`scripts/process-media.mjs\`: responsive AVIF/WebP, 24 px LQIP placeholders, H.264 video (1280 wide, muted) and art-directed detail crops (\`src/data/details.json\`).
- **Fonts**: Hubot Sans, Mona Sans and Azeret Mono — SIL Open Font License 1.1, subset by \`scripts/fonts/subset.py\`; licences in \`src/fonts/\`.
- **Open Graph cards** (\`public/og/\`, JPEG) are rendered from the site's own fonts and captures by \`scripts/og.mjs\` — one per page, including every post and review.
- **Blog and review media** (\`public/media/blog/\`, \`public/media/reviews/\`) are summarised at the end of this file.
- **Dialogs dismissed for capture only** are listed per asset (cookie banners and 21+ age confirmations on tobacco-retail pages). Nothing on the live sites was changed.

Total web media: ${(total / 1024 / 1024).toFixed(1)} MB across ${Object.keys(media).length} captures (a page only loads the sizes it shows).

| Asset | Source URL | Captured | Views & recordings | Placement on the new site | Dismissed for capture | Licensing | Web size |
|---|---|---|---|---|---|---|---|
${rows.join('\n')}
`;
// Blog and review media: produced by scripts/content/blog.mjs and reviews.mjs from the fetched pages.
const dirSize = (d) => { try { return fs.readdirSync(d).reduce((a, n) => a + fs.statSync(path.join(d, n)).size, 0); } catch { return 0; } };
const readJ = (f: string, d: any) => { try { return JSON.parse(fs.readFileSync(path.join(root, f), 'utf8')); } catch { return d; } };
const posts = readJ('src/data/blog.json', []);
const sums = readJ('src/data/blog-summaries.json', []);
const revs = readJ('src/data/reviews.json', []);
const imgCount = (html: string) => (html.match(/<img /g) || []).length;
const contentDoc = `

## Blog and review media

Made by \`scripts/content/blog.mjs\` and \`scripts/content/reviews.mjs\` from pages fetched on GitHub Actions (\`capture/content/\`). Images are Mousa's own (post covers and figures he published; screenshots of his own review pages); re-encoded to WebP at two widths. Nothing was bought or generated.

- **Blog:** ${posts.length} posts with pages (${posts.reduce((n: number, p: any) => n + (p.image ? 1 : 0) + imgCount(p.html), 0)} images) and ${sums.length} summary cards with their published covers — ${(dirSize(path.join(root, 'public/media/blog')) / 1024 / 1024).toFixed(1)} MB.
- **Reviews:** ${revs.length} reviews, ${revs.reduce((n: number, r: any) => n + r.sheets.length, 0)} sheets, each sheet's first screen as published plus the images inside the sheets — ${(dirSize(path.join(root, 'public/media/reviews')) / 1024 / 1024).toFixed(1)} MB.

| Review | Site reviewed | Observed | Sheets | Images in text | Source |
|---|---|---|---|---|---|
${revs.map((r: any) => `| ${r.brand} — ${r.kind} | ${r.site} | ${r.date} | ${r.sheets.length} | ${r.sheets.reduce((n: number, s: any) => n + imgCount(s.html), 0)} | ${r.source} |`).join('\n')}
`;
fs.writeFileSync(path.join(root, 'docs/asset-inventory.md'), assetDoc + contentDoc);

// Project inventory
const catLabel = Object.fromEntries(categories.map((c) => [c.id, c.label]));
const prow = entries.map((e, i) => {
  const lk: any = e.url ? linkStatus.get(e.url) : null;
  const check = lk ? (lk.ok ? `${lk.status}${lk.redirects ? ` → ${lk.finalUrl}` : ''}` : `${lk.status || lk.error}`) : 'not in link check';
  return `| ${String(i + 1).padStart(2, '0')} | ${e.family ? '↳ ' : ''}${e.title} | ${catLabel[e.category]} | ${e.what} | ${e.platform || '—'} | ${e.caseStudy ? `[/work/${e.caseStudy}/](../src/pages/work/%5Bslug%5D.astro)` : '—'} | ${e.url || '—'} | ${statusLabel[e.status]} | ${check} |`;
}).join('\n');
const projDoc = `# Project inventory

Generated by \`scripts/inventory.ts\` from \`src/data/work.ts\` (the archive the site renders) and the link check run on GitHub Actions (\`capture/reports/links.json\`, ${links.checkedAt.slice(0, 10)}).

- **${entries.length} entries** in the archive: ${categories.map((c) => `${entries.filter((e) => e.category === c.id).length} ${c.label.toLowerCase()}`).join(', ')}.
- **${cases.length} full case studies**: ${cases.map((c) => c.title).join(', ')}.
- **Reviews:** the six strongest and most recent are featured; the complete index stays at mousabatarseh.com/reviews/.
- **Excluded at Mousa's request:** the Job Search Log (/jobs/) and the DiaMedical Interview Trainer. Their live pages were not touched.
- **Merged:** CSV Mapper and Commerce Studio (same app); PTEE builds grouped as one family; DealProof, Northgate and the marketing-operations demo grouped under the Deals Operating System; the DiaMedical suite grouped under the lab; Wild Bill’s campaign pages grouped.
- **Link status** is what an automated request saw. \`403\` means the host blocks automated checks (Cloudflare challenges on some hosts) — the site may still load for people, so those rows are labelled “Host blocks automated checks” rather than removed.

| # | Project | Category | What it is | Platform | Case study | Live URL | Label on site | Link check |
|---|---|---|---|---|---|---|---|---|
${prow}
`;
fs.writeFileSync(path.join(root, 'docs/project-inventory.md'), projDoc);
console.log(`asset rows: ${rows.length}, project rows: ${entries.length}, media ${(total / 1024 / 1024).toFixed(1)} MB`);
