// The blog, as pages of this site. Content comes from src/data/blog.json, generated by
// scripts/content/blog.mjs from the fetched posts (capture/content/blog/).
import raw from './blog.json';
import rawSummaries from './blog-summaries.json';

export type BlogImage = { src: string; small: string; alt: string; w: number; h: number };
export type Post = {
  slug: string;
  title: string;
  date: string;
  modified: string | null;
  categories: string[];
  excerpt: string;
  minutes: number;
  words: number;
  image: BlogImage | null;
  source: string;
  html: string;
};

export const blogPosts = (raw as Post[]).slice().sort((a, b) => (a.date < b.date ? 1 : -1));

// Listed on the old blog index, but the full article isn't published anywhere (its link opens the index).
export type Summary = { slug: string; title: string; date: string; categories: string[]; excerpt: string; image: BlogImage | null };
export const blogSummaries = (rawSummaries as Summary[]).slice().sort((a, b) => (a.date < b.date ? 1 : -1));

// One bright tone per category, so a post's colour is the same on every page.
const TONES = ['var(--sky)', 'var(--peach)', 'var(--lemon)', 'var(--mint)', 'var(--blush)', 'var(--lilac)'];
const DOTS = ['var(--blue)', 'var(--tomato)', 'var(--sun)', 'var(--aqua)', 'var(--pink)', 'var(--violet)'];
export const categories = [...new Set(blogPosts.flatMap((p) => p.categories))].sort();
export const catKey = (c: string) => c.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
export const toneOf = (c?: string) => TONES[Math.max(0, categories.indexOf(c || '')) % TONES.length];
export const dotOf = (c?: string) => DOTS[Math.max(0, categories.indexOf(c || '')) % DOTS.length];
export const countIn = (c: string) => blogPosts.filter((p) => p.categories.includes(c)).length;

export function related(post: Post, n = 3) {
  const score = (p: Post) => p.categories.filter((c) => post.categories.includes(c)).length;
  return blogPosts.filter((p) => p.slug !== post.slug).map((p) => ({ p, s: score(p) })).sort((a, b) => b.s - a.s || (a.p.date < b.p.date ? 1 : -1)).slice(0, n).map((x) => x.p);
}
