// The reviews, as pages of this site. Content comes from src/data/reviews.json, generated by
// scripts/content/reviews.mjs from the fetched reviews (capture/content/reviews/). Every sentence is the review's own.
import raw from './reviews.json';

export type ReviewImage = { src: string; small: string; w: number; h: number; sw: number; alt: string };
export type Sheet = { n: string; title: string; kicker: string; html: string; words: number; shot: ReviewImage | null };
export type FullReview = {
  slug: string;
  brand: string;
  kind: string;
  title: string;
  site: string;
  focus: string[];
  date: string;
  sources: string;
  stat: { value: string; of: string; label: string };
  headline: string;
  lede: string;
  blurb: string;
  findings: { n: string; title: string; text: string }[];
  contents: string[];
  hero: ReviewImage | null;
  thumb: ReviewImage | null;
  disclaimer: string;
  minutes: number;
  sheets: Sheet[];
  source: string;
};

export const allReviews = (raw as FullReview[]).slice().sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : a.brand.localeCompare(b.brand)));
export const focusAreas = [...new Set(allReviews.flatMap((r) => r.focus))].sort();
export const focusKey = (f: string) => f.toLowerCase().replace(/&/g, 'and').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
export const statText = (r: FullReview) => (r.stat.of ? `${r.stat.value} / ${r.stat.of}` : r.stat.value);

// Bright tones cycle through the list; the text colour follows the ground.
export const REVIEW_TONES = [
  { bg: 'var(--pink)', fg: 'var(--ink)' },
  { bg: 'var(--lime)', fg: 'var(--ink)' },
  { bg: 'var(--violet)', fg: '#fff' },
  { bg: 'var(--sun)', fg: 'var(--ink)' },
  { bg: 'var(--aqua)', fg: 'var(--ink)' },
  { bg: 'var(--tomato)', fg: 'var(--ink)' },
];
export const toneFor = (slug: string) => REVIEW_TONES[Math.max(0, allReviews.findIndex((r) => r.slug === slug)) % REVIEW_TONES.length];
export const TINTS = ['var(--blush)', 'var(--mint)', 'var(--lilac)', 'var(--lemon)', 'var(--sky)', 'var(--peach)'];
export const tintFor = (slug: string) => TINTS[Math.max(0, allReviews.findIndex((r) => r.slug === slug)) % TINTS.length];

export function relatedReviews(r: FullReview, n = 3) {
  const score = (x: FullReview) => x.focus.filter((f) => r.focus.includes(f)).length;
  return allReviews.filter((x) => x.slug !== r.slug).map((x) => ({ x, s: score(x) })).sort((a, b) => b.s - a.s || (a.x.date < b.x.date ? 1 : -1)).slice(0, n).map((y) => y.x);
}
